-- ─────────────────────────────────────────────────────────────────────────────
-- 05_bookings.sql
-- Guest bookings — written by booking.ts Server Action.
-- Depends on: 00_helpers.sql, 01_profiles.sql
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Table ────────────────────────────────────────────────────────────────────
--
-- Design decisions (confirmed in contract audit):
--   • listing_slug TEXT (no FK to listings) — intentional denormalization.
--     Preserves booking data even if the listing is later deleted or slug changes.
--   • host_id / host_name are nullable — null when booking is against a
--     manually-seeded listing that has no profiles entry.
--   • status stores "confirmed" or "cancelled" only.
--     Display status (upcoming / active / completed) is derived at read time
--     by comparing check_in / check_out to today's date (see bookings.ts).
--   • adults + children stored separately (not merged into a single `guests` column).

CREATE TABLE IF NOT EXISTS public.bookings (
  id                 UUID        PRIMARY KEY,               -- generated by client Server Action
  reference          TEXT        NOT NULL UNIQUE,           -- "BDN-XXXXXXXX"

  -- Ownership
  user_id            UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  host_id            UUID        REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Listing snapshot (denormalized at write time; no FK — intentional)
  listing_slug       TEXT        NOT NULL,
  listing_category   TEXT        NOT NULL DEFAULT '',
  listing_title      TEXT        NOT NULL DEFAULT '',
  location           TEXT        NOT NULL DEFAULT '',
  image              TEXT        NOT NULL DEFAULT '',

  -- Stay details
  check_in           DATE        NOT NULL,
  check_out          DATE        NOT NULL,
  nights             INTEGER     NOT NULL DEFAULT 1  CHECK (nights >= 1),
  adults             INTEGER     NOT NULL DEFAULT 1  CHECK (adults >= 1),
  children           INTEGER     NOT NULL DEFAULT 0  CHECK (children >= 0),

  -- Pricing snapshot (denormalized at write time)
  subtotal           NUMERIC(10, 2) NOT NULL DEFAULT 0,
  service_fee        NUMERIC(10, 2) NOT NULL DEFAULT 0,
  total_price        NUMERIC(10, 2) NOT NULL DEFAULT 0,

  -- Guest info (collected at checkout; stored for host visibility)
  guest_name         TEXT        NOT NULL DEFAULT '',
  guest_email        TEXT        NOT NULL DEFAULT '',
  guest_phone        TEXT,
  guest_nationality  TEXT,
  special_requests   TEXT,

  -- Payment
  payment_method     TEXT        NOT NULL DEFAULT 'card',

  -- Host snapshot (denormalized; may be null for manually-seeded listings)
  host_name          TEXT,

  -- Workflow status
  status             TEXT        NOT NULL DEFAULT 'confirmed'
                                 CHECK (status IN ('confirmed', 'cancelled')),

  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT bookings_dates_check CHECK (check_out > check_in)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS bookings_user_id_idx      ON public.bookings (user_id);
CREATE INDEX IF NOT EXISTS bookings_host_id_idx      ON public.bookings (host_id);
CREATE INDEX IF NOT EXISTS bookings_listing_slug_idx ON public.bookings (listing_slug);
CREATE INDEX IF NOT EXISTS bookings_status_idx       ON public.bookings (status);
CREATE INDEX IF NOT EXISTS bookings_check_in_idx     ON public.bookings (check_in);
CREATE INDEX IF NOT EXISTS bookings_created_at_idx   ON public.bookings (created_at DESC);

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 1. Guests read their own bookings (user dashboard Bookings tab)
CREATE POLICY "bookings_read_own_as_guest"
  ON public.bookings
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- 2. Guests insert their own bookings (createBooking() Server Action)
--    The Server Action verifies auth.getUser() before calling insert, so the
--    policy enforces the same constraint at the database layer.
CREATE POLICY "bookings_insert_own"
  ON public.bookings
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- 3. Guests can update their own bookings (future: self-service cancellation)
CREATE POLICY "bookings_update_own_as_guest"
  ON public.bookings
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 4. Hosts read bookings for their listings (host dashboard Bookings tab)
--    Matches fetchHostBookings() which filters by host_id.
CREATE POLICY "bookings_read_own_as_host"
  ON public.bookings
  FOR SELECT
  TO authenticated
  USING (auth.uid() = host_id);

-- 5. Admins read all bookings
CREATE POLICY "bookings_admin_read_all"
  ON public.bookings
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- 6. Admins update any booking (future: admin-side cancellation / overrides)
CREATE POLICY "bookings_admin_update_all"
  ON public.bookings
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
