import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "picsum.photos",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
      {
        // Host avatars generated by the admin approval action
        protocol: "https",
        hostname: "i.pravatar.cc",
      },
      {
        // Supabase Storage (for future real image uploads)
        protocol: "https",
        hostname: "*.supabase.co",
      },
      {
        // Allow any https image URL (hosts can paste external image URLs)
        protocol: "https",
        hostname: "**",
      },
    ],
  },
};

export default nextConfig;
